AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bia-serverless

  Sample SAM Template for bia-serverless
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
  Api:
    Cors:
      AllowMethods: "'GET, PUT, POST, DELETE, OPTIONS'"
      AllowOrigin: "'*'"
      AllowHeaders: "'Content-type, x-api-key'"
Resources:
  TarefasFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: lambda.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        #HelloWorld:
          #Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          #Properties:
          #  Path: /hello
          #  Method: get
        Ping:
          Type: Api
          Properties:
            Path: /api/ping
            Method: get
        Versao:
          Type: Api
          Properties:
            Path: /api/versao
            Method: get
        GetTarefas:
          Type: Api
          Properties:
            Path: /api/tarefas
            Method: get
        PostTarefas:
          Type: Api
          Properties:
            Path: /api/tarefas
            Method: post
        GetTarefa:
          Type: Api
          Properties:
            Path: /api/tarefas/{uuid}
            Method: get
        UpdatePriority:
          Type: Api
          Properties:
            Path: /api/tarefas/update_priority/{uuid}
            Method: put
        DeleteTarefas:
          Type: Api
          Properties:
            Path: /api/tarefas/{uuid}
            Method: delete
      Environment:
        Variables:
          DB_HOST: bia-db.csba0wu66tf6.us-east-1.rds.amazonaws.com
          DB_PORT: 5432
          DB_USER: postgres
          DB_PWD: ZF:M:vyUEwh$W(OTL*iBZrS]5Q[v
      VpcConfig:
        SecurityGroupIds:
          - sg-0acb681a80d7314fe
        SubnetIds:
          - subnet-05fe98db978720582
          - subnet-06bb33dfe9ad6af8e
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TarefasApi:
    Description: "API Gateway endpoint URL for Prod stage for Tarefas function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/api/tarefas/"
  TarefasFunction:
    Description: "Tarefas Lambda Function ARN"
    Value: !GetAtt TarefasFunction.Arn
  TarefasFunctionIamRole:
    Description: "Implicit IAM Role created for Tarefas function"
    Value: !GetAtt TarefasFunctionRole.Arn
