AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bia-serverless

  Sample SAM Template for bia-serverless
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: "Comma-separated list of Security Group IDs for the Lambda function"
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "Comma-separated list of Subnet IDs for the Lambda function"
  DBName:
    Type: String
    Description: "Database name for the Lambda function"
  DBUser:
    Type: String
    Description: "Database user for the Lambda function"
  DBPassword:
    Type: String
    Description: "Database password for the Lambda function"
    NoEcho: true
  DBHost:
    Type: String
    Description: "Database host for the Lambda function"
  DBPort:
    Type: Number
    Description: "Database port for the Lambda function"
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    VpcConfig:
      SecurityGroupIds:
        - !Ref SecurityGroupIds
      SubnetIds:
        - !Ref SubnetIds
    Environment:
      Variables:
        DB_HOST: !Ref DBHost
        DB_PORT: !Ref DBPort
        DB_NAME: !Ref DBName
        DB_USER: !Ref DBUser
        DB_PWD: !Ref DBPassword
  Api:
    Cors:
      AllowMethods: "'GET, PUT, POST, DELETE, OPTIONS'"
      AllowOrigin: "'*'"
      AllowHeaders: "'Content-type, x-api-key'"
Resources:
  TarefasFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: lambda.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        #HelloWorld:
          #Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          #Properties:
          #  Path: /hello
          #  Method: get
        Ping:
          Type: Api
          Properties:
            Path: /api/ping
            Method: get
        Versao:
          Type: Api
          Properties:
            Path: /api/versao
            Method: get
        GetTarefas:
          Type: Api
          Properties:
            Path: /api/tarefas
            Method: get
        PostTarefas:
          Type: Api
          Properties:
            Path: /api/tarefas
            Method: post
        GetTarefa:
          Type: Api
          Properties:
            Path: /api/tarefas/{uuid}
            Method: get
        UpdatePriority:
          Type: Api
          Properties:
            Path: /api/tarefas/update_priority/{uuid}
            Method: put
        DeleteTarefas:
          Type: Api
          Properties:
            Path: /api/tarefas/{uuid}
            Method: delete
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TarefasApi:
    Description: "API Gateway endpoint URL for Prod stage for Tarefas function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/api/tarefas/"
  TarefasFunction:
    Description: "Tarefas Lambda Function ARN"
    Value: !GetAtt TarefasFunction.Arn
  TarefasFunctionIamRole:
    Description: "Implicit IAM Role created for Tarefas function"
    Value: !GetAtt TarefasFunctionRole.Arn
