version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - node -v
      - npm -v
  build:
    commands:
      - npm install --legacy-peer-deps --loglevel=error
      - VITE_API_URL=http://bia-alb-815738101.us-east-1.elb.amazonaws.com SKIP_PREFLIGHT=true npm run build -- prefix client
      - echo Running Unit Tests
      - npm test